spring:
  profiles:
    active: dev
  messages:
    encoding: utf-8
    basename: ValidationMessages
license:
  notification-type: emailLicenseNotificationAdapter
  email:
    sender-name: Reboot
    retry-count: 3
  sms:
    sender-number: "010-1234-5678"
    retry-count: 2